### ISSUE TITLE
Add this to Melpa

### ISSUE THREAD

**Issue by nickdrozd** [gonsie/ox-jekyll-md#1]
This was exactly the package I was looking for! Have you considered putting it on Melpa? That way I wouldn't have to maintain local copies 🐈

**Comment by gonsie** [comment]
I'm so glad that you find it useful! I will definitely add it to Melpa 😄

**Comment by gonsie** [comment]
Submitted via melpa/melpa#5688

**Comment by gonsie** [comment]
After 24 glorious hours in melpa, the package was removed because of a name conflict with org-octpress (something I should have caught sooner). Anyways, this package is now named `ox-jekyll-md` and is submitted to melpa at melpa/melpa#5714
